name: Build & Release Foundry Module

on:
  push:
    tags:
      - 'v*'  # triggers only when pushing tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build the module
        run: npm run build

      - name: Zip the release files
        run: cd download && zip -r ../sheexcel_latest.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: sheexcel_latest.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
